workflows:
  android:
    name: Build APK
    max_build_duration: 10
    environment:
      android:
        gradle: true
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
