workflows:
  android:
    name: Build APK
    max_build_duration: 10
    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
    scripts:
      - name: Build APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
